/** @format */
const mongoose = require("mongoose");

const FranchiseApplicationSchema = new mongoose.Schema({
  fullName: { type: String },
  fatherHusbandName: { type: String },
  dateOfBirth: { type: Date },
  gender: { type: String },
  nationality: { type: String },
  maritalStatus: { type: String },
  panNumber: { type: String },
  aadharNumber: { type: String },
  passportNumber: { type: String },
  mobileNumber: { type: String },
  alternateMobileNumber: { type: String },
  email: { type: String },
  preferredCommunication: { type: String },
  residentialStreet: { type: String },
  residentialCity: { type: String },
  residentialDistrict: { type: String },
  residentialState: { type: String },
  residentialPinCode: { type: String },
  businessName: { type: String },
  businessType: { type: String },
  gstNumber: { type: String },
  officeAddress: { type: String },
  officeCity: { type: String },
  officeDistrict: { type: String },
  officeState: { type: String },
  officePinCode: { type: String },
  numberOfEmployees: { type: Number },
  franchisePinCode: { type: String },
  premisesOwnership: { type: String },
  totalSpace: { type: String },
  warehouseSpace: { type: String },
  parkingFacility: { type: String },
  officeSetup: { type: String },
  investmentCapacity: { type: String },
  investmentSource: { type: String },
  hasLoans: { type: Boolean },
  loanDetails: { type: String },
  expectedRevenue: { type: String },
  hasCommercialVehicles: { type: Boolean },
  vehicleDetails: { type: String },
  isFamiliarWithLogistics: { type: Boolean },
  hasLogisticsExperience: { type: Boolean },
  experienceDetails: { type: String },
  staffCount: { type: Number },
  education: { type: String },
  professionalBackground: { type: String },
  certifications: { type: String },
  hasOtherFranchise: { type: Boolean },
  franchiseDetails: { type: String },
  hasLegalIssues: { type: Boolean },
  legalDetails: { type: String },
  reference1Name: { type: String },
  reference1Contact: { type: String },
  reference1Relationship: { type: String },
  reference2Name: { type: String },
  reference2Contact: { type: String },
  reference2Relationship: { type: String },
  bankName: { type: String },
  bankBranch: { type: String },
  accountHolderName: { type: String },
  accountNumber: { type: String },
  ifscCode: { type: String },
  upiId: { type: String },
  photo: { type: String },
  aadharCard: { type: String },
  aadharBack: { type: String },
  panCard: { type: String },
  cancelCheque: { type: String },
  status: { type: String, default: "pending" }, // original status field
  // Cumulative status flags
  approved: { type: Boolean, default: false },
  agreementSent: { type: Boolean, default: false },
  oneTimeFeePaid: { type: Boolean, default: false },
  passport: { type: String },
  createdAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model(
  "FranchiseApplication",
  FranchiseApplicationSchema
);
